<?php

/**
 * @var $art
 */

?>



<div id="flipbook">
    <div class="hard"> Turn.js </div>
    <div class="hard"></div>
    <div>
        <div class="row">
            <?php foreach ($art->getImages() as $image) : ?>
                <div class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                        <img
                                src="<?= $this->basePath($image->getPath()) ?>"
                                alt="<?= $image->getAlt() ?>"
                        >
                        <div class="caption">
                            wqwqwq
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <div><h2>1</h2></div>
    <div><h2>2</h2></div>
    <div></div>
    <div class="hard text-center">
        <h2>Я</h2>
        <h2>Люблю</h2>
        <h2>Свою</h2>
        <h2>Дашульку</h2>
    </div>
    <div class="hard"></div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $("#flipbook").turn({
            // width: 400,
            // height: 300,
            // autoCenter: true
        });
    });
</script>